Add capped minter v2
zksync-association/zk-governance pull request #20
Opened 2024-12-18 02:10 UTC by alexkeating

#### Description

- The changes can be found in the following issues.

https://github.com/ScopeLift/zk-governance/issues/2
https://github.com/ScopeLift/zk-governance/issues/5
https://github.com/ScopeLift/zk-governance/issues/5
https://github.com/ScopeLift/zk-governance/issues/6
https://github.com/ScopeLift/zk-governance/issues/7
https://github.com/ScopeLift/zk-governance/issues/8
https://github.com/ScopeLift/zk-governance/issues/21
https://github.com/ScopeLift/zk-governance/issues/26

2024-12-18 22:19 UTC, saxenism requested changes

2024-12-19 07:21 UTC, vladbochok commented on l2-contracts/src/ZkCappedMinterV2.sol
> +/// @custom:security-contact security@zksync.io
```suggestion
/// @custom:security-contact security@matterlabs.dev
```

2024-12-19 07:21 UTC, vladbochok commented on l2-contracts/src/ZkCappedMinterV2.sol
> +  /// [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.6/contracts/access/AccessControlDefaultAdminRules.sol#L82).
Why you don't inherit `accessControlDefaultAdminRules` and do this modification here?

At least, it is not possible to transfer ownership in the current configuration.

2024-12-19 07:21 UTC, vladbochok commented on l2-contracts/src/ZkCappedMinterV2.sol
> +    require(role != DEFAULT_ADMIN_ROLE, "AccessControl: can't directly grant default admin role");
Nit: Curtom error for consistency

2024-12-19 07:22 UTC, vladbochok commented
@alexkeating LGTM! 

What is the key difference between ZkCappedMinter V1 and what use cases V2 covers?

2024-12-19 13:07 UTC, alexkeating commented on l2-contracts/foundry.toml
> +  invariant = { runs = 500 }
We are happy to keep the original numbers. We halved them to speed up the build, with the current numbers a build takes about 42 minutes.

2024-12-19 13:12 UTC, alexkeating commented on l2-contracts/src/ZkCappedMinterV2.sol
> +    MINTABLE.mint(_to, _amount);
This seems like overkill. In reality, the mintable contract will either be the zk token or another ZKCappedMinterV2 contract. If someone uses a contract where the mint function does not work as expected they can deploy new capped minter that has a mintable with a mint function that does work.

2024-12-19 13:13 UTC, alexkeating commented on l2-contracts/src/ZkCappedMinterV2.sol
> +/// @custom:security-contact security@zksync.io
We can make this change

2024-12-19 13:50 UTC, alexkeating commented
> @alexkeating LGTM!
> 
> What is the key difference between ZkCappedMinter V1 and what use cases V2 covers?

Feel free to look at the issues in the description for a deeper understanding. I included  some high level bullets below:

- Admin can assign minter role
- Admin can assign pauser role
- Admin can pause the ability to mint
- Admin can close minter, once closed a minter stays closed
- Minters can be nested now with other minters
- Minters can start minting at a specific time and can prevent minting after a specific time

2024-12-19 15:12 UTC, vladbochok commented on l2-contracts/src/ZkCappedMinterV2.sol
> +  /// [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.6/contracts/access/AccessControlDefaultAdminRules.sol#L82).
Fair enough. What do you about the issue I raised? It may be very important to transfer admin rights to different address?

2024-12-23 17:45 UTC, alexkeating commented on l2-contracts/src/ZkCappedMinterV2.sol
> +  /// [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.6/contracts/access/AccessControlDefaultAdminRules.sol#L82).
I don't think switching admins is a huge issue. Typically admins will be a multisig and let's say the admin no longer wants to manage a capped minter they can give another capped minter with a different admin the `MINTER_ROLE`, and renounce their own role.

2025-01-06 09:38 UTC, vladbochok commented on l2-contracts/src/ZkCappedMinterV2.sol
> +  function grantRole(bytes32 role, address account) public virtual override {
@alexkeating if audits are already done, please make a doc comment in the contract header that ownership can't be transferred.

Otherwise we should implement  `transferOwnership` function to transfer default admin rights.

2025-01-06 13:31 UTC, alexkeating commented on l2-contracts/src/ZkCappedMinterV2.sol
> +  function grantRole(bytes32 role, address account) public virtual override {
https://github.com/zksync-association/zk-governance/pull/20/commits/ab6b48bf50417f13767e330b36752ee8d6dde1b9

2025-01-07 13:36 UTC, merged